[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rnd"
version = "0.1.0"
dependencies = [
    "accelerate",
    "torch>=2.8",
    "transformers>=5.0.0",
    "rich"
]

[project.optional-dependencies]
linting = ["ruff>=0.13.2", "pre-commit>=4.0.0"]

[tool.setuptools]
packages = ["rnd"]

[tool.ruff]
line-length = 100
target-version = "py311"
show-fixes = false
extend-exclude = ["*.ipynb"]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # flake8-bugbear
    "B",
    # pyupgrade
    "UP",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # unsafe yaml loading
    "S506", 
    # flake8-pie
    "PIE",
]
task-tags = ["TODO", "FIXME"]
ignore = ["D417", "D10", "F841", "E501"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]

[tool.ruff.lint.isort]
known-first-party = []
known-third-party = []
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
combine-as-imports = true
split-on-trailing-comma = false
lines-between-types = 1